{% set name = "qt6-main" %}
{% set version = "6.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/single/qt-everywhere-src-{{ version }}.tar.xz
    md5: 15e2530292b65a2b3dc23fc03f140796
    patches:
      # qtbase
      - patches/0003-qtbase-use-better-clang-optimize-size.patch

      # qtdeclarative
      # $SRC_DIR/qtdeclarative/src/quicktestutils/qml/testhttpserver_p.h:18:10: fatal error: QTcpServer: No such file or directory
      - patches/0034-qtdeclarative-qtcpserver-include.patch

  - url: https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_12_0_rc2.7z     # [win64]
    sha256: 2a0d2f92c60e0962ef5f6039d3793424c6f39e49ba27ac04a5b21ca4ae012e15                                      # [win64]
    folder: opengl32sw                                                                                            # [win64]

build:
  number: 3
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt6-main', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /usr/lib/libbsm.0.dylib  # [osx]
    - /usr/lib/libcups.2.dylib  # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libsandbox.1.dylib  # [osx]
    - '/System/Library/Frameworks/CoreLocation.framework/**'  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]

    # For fontconfig + freetype
    - pkg-config                         # [unix]
    - make                               # [unix]
    - cmake
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - m2-gperf                           # [win]
    - m2-bison                           # [win]
    - m2-flex                            # [win]
    - m2-patch                           # [win]
    - curl                               # [win]
    - perl 5
    # libclang is required in order to enable simultaneous x86_64 and
    # arm64 support for QDoc
    - libclang                           # [build_platform != target_platform]
    # Although these should be host-only dependencies, they are needed when
    # cross-compiling arm64 binaries on x86_64 since llvm-config (host/arm64)
    # cannot be executed on x86_64 to locate libclang successfully
    - llvmdev                           # [build_platform != target_platform]
    - clangdev                          # [build_platform != target_platform]
    # native libs
    - icu                               # [build_platform != target_platform]
    - double-conversion                 # [build_platform != target_platform]
    - libtiff                           # [build_platform != target_platform]
    - libwebp                           # [build_platform != target_platform]
    - dbus                              # [build_platform != target_platform and linux]
    - fontconfig                        # [build_platform != target_platform and linux]
    - freetype                          # [build_platform != target_platform and linux]
    - harfbuzz                          # [build_platform != target_platform]
    - glib                              # [build_platform != target_platform]
    - gst-plugins-base {{ gstreamer }}  # [build_platform != target_platform]
    - gstreamer                         # [build_platform != target_platform]
    - pulseaudio                        # [build_platform != target_platform and linux]
    - libxml2                           # [build_platform != target_platform and linux]
    - libxkbcommon                      # [build_platform != target_platform and linux]
    - zlib                              # [build_platform != target_platform]
    - libxcb                            # [build_platform != target_platform and linux]
    - libdrm                            # [build_platform != target_platform and linux]
    - openssl                           # [build_platform != target_platform]
    - libcups                           # [build_platform != target_platform and linux]
    - zstd                              # [build_platform != target_platform]
    - krb5                              # [build_platform != target_platform]
    - jpeg                              # [build_platform != target_platform]
    - libpng                            # [build_platform != target_platform]
    - libsqlite                         # [build_platform != target_platform]
    - mysql-devel                       # [build_platform != target_platform]
    - postgresql                        # [build_platform != target_platform]
    - pcre2                             # [build_platform != target_platform]
  host:
    # For pkg-config gl, fontconfig + freetype
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - harfbuzz
    - glib
    - gst-plugins-base  {{ gstreamer }}  # [unix]
    # gstreamer plugin not supported on win32: https://bugreports.qt.io/browse/QTBUG-107073
    - gstreamer                          # [unix]
    - pulseaudio                         # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    - icu
    # jpeg-turbo currently has some conflicting issues in conda-forge
    # see: https://github.com/conda-forge/conda-forge.github.io/issues/673
    - jpeg
    - libpng
    - libsqlite
    - mysql-devel                        # [not win]
    - postgresql                         # [not win]
    - pcre2
    - zlib
    - libxcb                             # [linux]
    - libdrm                             # [linux]
    - openssl
    # For QDoc
    # http://doc.qt.io/Qt-5/qdoc-guide-clang.html
    # Only libclang is needed, but needs the full package for detection.
    - llvmdev
    - clangdev
    # Ensure that build and host have the same clang version on osx
    # otherwise qt6 may be out of sync compared to the pinned compiler
    # version
    - libclang {{ cxx_compiler_version }}  # [osx]
    - libclang                             # [not osx]
    - libcups                            # [linux]
    - zstd
    - alsa-lib                           # [linux]
    - krb5
    - double-conversion
    - libtiff
    - libwebp
  run:
    - libxcb                             # [linux]
    # Adding the following xcb-util run requirements resolves issue
    # that may exhibit as segfault due to missing libraries
    # in some lighter weight linux installations
    # https://github.com/conda-forge/qt-main-feedstock/issues/32
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - {{ pin_compatible("libclang") }}
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
    - qt {{ version }}

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - make                               # [unix]
    - cmake
  files:
    - test/main-qtwebengine.cpp
    - test/main.cpp
    - test/main.qml
    - test/qml.qrc
    - test/qrc_qml.cpp
    - test/test_qmimedatabase.cpp
    - test/CMakeLists.txt
  commands:
    {% set qt_libs = ["Core",
                      "Gui",
                      "Network",
                      "OpenGL",
                      "OpenGLWidgets",
                      "PrintSupport",
                      "Sensors",
                      "ShaderTools",
                      "Svg",
                      "Test",
                      "Qml",
                      "Quick",
                      "Widgets",
                      "Xml"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1  # [win]
    {% endfor %}
    - test -f $PREFIX/lib/qt6/plugins/platforms/libqxcb.so  # [linux]
    - test -f $PREFIX/lib/qt6/plugins/sqldrivers/libqsqlite${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/qt6/plugins/imageformats/libqtiff${SHLIB_EXT}  # [unix]
    - qmake6 --version

about:
  home: https://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPL3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
    - Tobias-Fischer
    - matthiasdiener
    - jschueller
