bot:
  abi_migration_branches:
  - qt5
build_platform:
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
workflow_settings:
  build_workspace_dir:
  - os: win
    value: C:\bld\
  free_disk_space: quick
