azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - qt6
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: default
  linux_ppc64le: default
  # Note: linux_ppc64le is currently build manually by @matthiasdiener
remote_ci_setup:
- liblief=0.11.5
- conda-forge-ci-setup=3
test_on_native_only: true
