workflow_settings:
  build_workspace_dir:
    - value: C:\bld\
      os: win
  free_disk_space: quick
bot:
  abi_migration_branches:
  - qt5
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
